import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { parseArgs } from 'node:util';

import { z } from 'zod';

import type { LegalChunk } from '../src/rag/ingestion/legal-section-chunker.js';
import type { RagEvidence } from '../src/rag/rag-service.js';
import { ProvisionGraph } from '../src/rag/retrieval/provision-graph.js';
import {
  DeterministicClaimVerifier,
  extractNumbers,
  isNegated,
} from '../src/rag/verification/claim-verifier.js';

// Measures the claim verifier's false acceptances and false rejections.
//
// Negative items are generated by perturbing real sentences of the indexed
// Companies Act text, so each label follows from the construction: the
// perturbed claim is not supported by the passage it is checked against. The
// same sentences unperturbed (verbatim and with a correct section citation) are
// positives. Hand-written paraphrases in data/eval/claim-verifier-
// paraphrases.json add non-verbatim positives. None of this is legal review; a
// lexical verifier that passes a perturbation may still be wrong about law.
//
// Partitions:
//   dev     Companies Act sections used to design the verifier;
//   test    the other Companies Act sections (used repeatedly during tuning);
//   unseen  sections of four other Acts (LLP, Trade Marks, FEMA, CGST) that the
//           verifier was never tuned on. Built the same way, it measures how
//           the rules generalise. It is only reported when requested, so it
//           cannot be consulted while tuning.
//
// Usage: pnpm eval:verifier -- [--partitions dev,test,unseen] [--out path]

const DEV_SECTIONS = new Set(['2', '135', '149', '173', '174', '188']);

const { values } = parseArgs({
  args: process.argv.slice(2).filter((argument) => argument !== '--'),
  options: {
    corpus: {
      type: 'string',
      default: 'data/sections/companies-act-2013.sections.json',
    },
    paraphrases: { type: 'string', default: 'data/eval/claim-verifier-paraphrases.json' },
    unseen: { type: 'string', default: 'data/eval/unseen-laws.sections.json' },
    'unseen-paraphrases': {
      type: 'string',
      default: 'data/eval/claim-verifier-paraphrases-unseen.json',
    },
    partitions: { type: 'string', default: 'dev,test' },
    out: { type: 'string' },
  },
});

const unseenSchema = z.object({
  schemaVersion: z.literal('legal-bot-unseen-sections-v1'),
  acts: z.array(
    z.object({
      act: z.string(),
      documentId: z.string(),
      sha256: z.string(),
      officialSourceUrl: z.string().nullable(),
      sections: z.array(z.object({ section: z.string(), heading: z.string(), text: z.string() })),
    }),
  ),
});
const unseenParaphraseSchema = z
  .object({
    schemaVersion: z.literal('legal-bot-claim-paraphrases-unseen-v1'),
    reviewNote: z.string().min(1),
    items: z
      .array(
        z
          .object({
            id: z.string().min(1),
            act: z.string().min(1),
            section: z.string(),
            claim: z.string().min(20),
            sourceExcerpt: z.string().min(20),
          })
          .strict(),
      )
      .min(1),
  })
  .strict();

const paraphraseSchema = z
  .object({
    schemaVersion: z.literal('legal-bot-claim-paraphrases-v1'),
    reviewNote: z.string().min(1),
    items: z
      .array(
        z
          .object({
            id: z.string().min(1),
            section: z.string(),
            claim: z.string().min(20),
            sourceExcerpt: z.string().min(20),
          })
          .strict(),
      )
      .min(1),
  })
  .strict();

type Label = 'supported' | 'not_supported';
type Partition = 'dev' | 'test' | 'unseen';
const requested = new Set(values.partitions.split(',').map((item) => item.trim()));
interface Item {
  id: string;
  partition: Partition;
  kind: string;
  label: Label;
  section: string;
  claim: string;
  evidence: RagEvidence[];
}

const graph = await ProvisionGraph.fromFile(resolve(process.cwd(), values.corpus));
const paraphrases = paraphraseSchema.parse(
  JSON.parse(await readFile(resolve(process.cwd(), values.paraphrases), 'utf8')),
);

const items: Item[] = [];
const sections = [...new Set(graph.chunks.map((chunk) => chunk.sectionNumber.toUpperCase()))]
  .filter((section) => /^\d+$/u.test(section))
  .sort((left, right) => Number(left) - Number(right));

for (const section of sections) {
  const chunk = graph.representative(section);
  if (!chunk) continue;
  const distractor = distractorFor(section);
  if (!distractor) continue;
  addPerturbations(
    DEV_SECTIONS.has(section) ? 'dev' : 'test',
    section,
    section,
    chunk.text,
    distractor.sectionNumber,
    [toEvidence(chunk), toEvidence(distractor)],
  );
}

// Unseen laws: the same construction over sections of four other Acts.
const unseen = unseenSchema.parse(
  JSON.parse(await readFile(resolve(process.cwd(), values.unseen), 'utf8')),
);
for (const act of unseen.acts) {
  const numbered = act.sections.filter((item) => /^\d+$/u.test(item.section));
  for (const [index, item] of numbered.entries()) {
    const next = numbered[(index + 1) % numbered.length]!;
    if (next.section === item.section) continue;
    addPerturbations(
      'unseen',
      `${act.act}#${item.section}`,
      item.section,
      stripSectionLabel(item.text),
      next.section,
      [unseenEvidence(act, item), unseenEvidence(act, next)],
    );
  }
}

function addPerturbations(
  partition: Partition,
  key: string,
  section: string,
  text: string,
  distractorSection: string,
  evidence: RagEvidence[],
) {
  const sentence = pickSentence(text);
  if (!sentence) return;
  const add = (kind: string, label: Label, claim: string) =>
    items.push({ id: `${key}-${kind}`, partition, kind, label, section, claim, evidence });

  add('verbatim', 'supported', sentence);
  add('cited', 'supported', `Under Section ${section}, ${lowerFirst(sentence)}`);

  const negated = isNegated(sentence)
    ? sentence.replace(/\bshall not\b/u, 'shall')
    : sentence.replace(/\bshall\b/u, 'shall not');
  if (negated !== sentence) add('negation', 'not_supported', negated);

  const renumbered = changeNumber(sentence);
  if (renumbered) add('number', 'not_supported', renumbered);

  if (/\bshall\b/u.test(sentence) && !/\bmay\b/u.test(sentence))
    add('modality', 'not_supported', sentence.replace(/\bshall\b/gu, 'may'));

  add(
    'wrong_section',
    'not_supported',
    `Under Section ${distractorSection}, ${lowerFirst(sentence)}`,
  );
  add(
    'fabricated_section',
    'not_supported',
    `Under Section 9${section.padStart(2, '0')}, ${lowerFirst(sentence)}`,
  );
  if (/\b(?:provided that|except|unless|other than)\b/iu.test(text))
    add(
      'denies_exception',
      'not_supported',
      `${sentence.replace(/[.:;]$/u, '')}, without any exception.`,
    );
}

for (const item of paraphrases.items) {
  const chunk = graph.representative(item.section);
  if (!chunk) throw new Error(`Paraphrase ${item.id} cites missing section ${item.section}`);
  if (!normalize(chunk.text).includes(normalize(item.sourceExcerpt)))
    throw new Error(`Paraphrase ${item.id} excerpt is not in Section ${item.section}`);
  const distractor = distractorFor(item.section);
  items.push({
    id: `paraphrase-${item.id}`,
    partition: DEV_SECTIONS.has(item.section) ? 'dev' : 'test',
    kind: 'paraphrase',
    label: 'supported',
    section: item.section,
    claim: item.claim,
    evidence: [toEvidence(chunk), ...(distractor ? [toEvidence(distractor)] : [])],
  });
}

const unseenParaphrases = unseenParaphraseSchema.parse(
  JSON.parse(await readFile(resolve(process.cwd(), values['unseen-paraphrases']), 'utf8')),
);
for (const item of unseenParaphrases.items) {
  const act = unseen.acts.find((entry) => entry.act === item.act);
  const numbered = act?.sections.filter((entry) => /^\d+$/u.test(entry.section)) ?? [];
  const index = numbered.findIndex((entry) => entry.section === item.section);
  if (!act || index < 0) throw new Error(`Paraphrase ${item.id} cites a missing section`);
  const source = numbered[index]!;
  if (!normalize(source.text).includes(normalize(item.sourceExcerpt)))
    throw new Error(`Paraphrase ${item.id} excerpt is not in section ${item.section}`);
  const next = numbered[(index + 1) % numbered.length]!;
  items.push({
    id: `unseen-paraphrase-${item.id}`,
    partition: 'unseen',
    kind: 'paraphrase',
    label: 'supported',
    section: item.section,
    claim: item.claim,
    evidence: [unseenEvidence(act, source), unseenEvidence(act, next)],
  });
}

const verifier = new DeterministicClaimVerifier();
const results: Array<
  Omit<Item, 'evidence'> & {
    evidence: string[];
    accepted: boolean;
    statuses: string[];
    reasons: string[];
  }
> = [];
for (const item of items) {
  if (!requested.has(item.partition)) continue;
  const report = await verifier.verify(item.claim, item.evidence);
  // An item counts as accepted only if every extracted claim is supported.
  const accepted = report.claimCount > 0 && report.supportedClaimCount === report.claimCount;
  results.push({
    ...item,
    evidence: item.evidence.map((entry) => entry.sectionIdentifier),
    accepted,
    statuses: report.claims.map((claim) => claim.status),
    reasons: [...new Set(report.claims.flatMap((claim) => claim.reasons))],
  });
}

const summary = Object.fromEntries(
  (['dev', 'test', 'unseen'] as const)
    .filter((partition) => requested.has(partition))
    .map((partition) => [
      partition,
      summarize(results.filter((item) => item.partition === partition)),
    ]),
);
const report = {
  generatedAt: new Date().toISOString(),
  evidenceClass:
    'deterministic claim verifier on perturbed and paraphrased sentences from the indexed Companies Act, 2013 reproduction; labels follow from construction (perturbation) or AI-written paraphrase review, not legal review',
  corpusSha256: createHash('sha256')
    .update(await readFile(resolve(process.cwd(), values.corpus)))
    .digest('hex'),
  paraphrasesSha256: createHash('sha256')
    .update(await readFile(resolve(process.cwd(), values.paraphrases)))
    .digest('hex'),
  devSections: [...DEV_SECTIONS],
  unseenSha256: createHash('sha256')
    .update(await readFile(resolve(process.cwd(), values.unseen)))
    .digest('hex'),
  unseenParaphrasesSha256: createHash('sha256')
    .update(await readFile(resolve(process.cwd(), values['unseen-paraphrases'])))
    .digest('hex'),
  // Hash of the generated items, so a report proves which frozen items it measured.
  unseenItemsSha256: createHash('sha256')
    .update(
      JSON.stringify(
        items
          .filter((item) => item.partition === 'unseen')
          .map((item) => [item.id, item.label, item.claim]),
      ),
    )
    .digest('hex'),
  summary,
  items: results,
};
if (values.out)
  await writeFile(resolve(process.cwd(), values.out), `${JSON.stringify(report, null, 2)}\n`);
for (const [partition, value] of Object.entries(summary)) {
  process.stdout.write(`\n## ${partition}\n`);
  process.stdout.write(
    `${'kind'.padEnd(20)}${'label'.padEnd(15)}${'n'.padEnd(6)}${'accepted'.padEnd(10)}rate [95% CI]\n`,
  );
  for (const row of value.byKind)
    process.stdout.write(
      `${row.kind.padEnd(20)}${row.label.padEnd(15)}${String(row.n).padEnd(6)}${String(row.accepted).padEnd(10)}${row.acceptRate.toFixed(3)} [${row.ci[0].toFixed(3)}, ${row.ci[1].toFixed(3)}]\n`,
    );
  process.stdout.write(
    `falseAcceptanceRate ${value.falseAcceptanceRate.rate.toFixed(3)} [${value.falseAcceptanceRate.ci.map((x) => x.toFixed(3)).join(', ')}] (n=${value.falseAcceptanceRate.n})\n` +
      `falseRejectionRate  ${value.falseRejectionRate.rate.toFixed(3)} [${value.falseRejectionRate.ci.map((x) => x.toFixed(3)).join(', ')}] (n=${value.falseRejectionRate.n})\n`,
  );
}

function summarize(rows: Array<{ kind: string; label: Label; accepted: boolean }>) {
  const kinds = [...new Set(rows.map((row) => `${row.kind}|${row.label}`))];
  const byKind = kinds.map((key) => {
    const [kind, label] = key.split('|') as [string, Label];
    const subset = rows.filter((row) => row.kind === kind && row.label === label);
    const accepted = subset.filter((row) => row.accepted).length;
    return {
      kind,
      label,
      n: subset.length,
      accepted,
      acceptRate: accepted / subset.length,
      ci: wilson(accepted, subset.length),
    };
  });
  const negatives = rows.filter((row) => row.label === 'not_supported');
  const positives = rows.filter((row) => row.label === 'supported');
  const fa = negatives.filter((row) => row.accepted).length;
  const fr = positives.filter((row) => !row.accepted).length;
  return {
    byKind,
    falseAcceptanceRate: {
      n: negatives.length,
      count: fa,
      rate: fa / Math.max(1, negatives.length),
      ci: wilson(fa, negatives.length),
    },
    falseRejectionRate: {
      n: positives.length,
      count: fr,
      rate: fr / Math.max(1, positives.length),
      ci: wilson(fr, positives.length),
    },
  };
}

function wilson(successes: number, n: number): [number, number] {
  if (n === 0) return [0, 1];
  const z = 1.96;
  const p = successes / n;
  const denominator = 1 + (z * z) / n;
  const centre = p + (z * z) / (2 * n);
  const margin = z * Math.sqrt((p * (1 - p)) / n + (z * z) / (4 * n * n));
  return [
    Math.max(0, (centre - margin) / denominator),
    Math.min(1, (centre + margin) / denominator),
  ];
}

// First self-contained operative sentence: starts a sub-section, contains
// "shall", and is short enough to be a single claim.
function pickSentence(text: string): string | null {
  const units = text
    .normalize('NFKC')
    .replace(/\s+/gu, ' ')
    .split(/(?<=[.;:])\s+(?=\(\d{1,3}[A-Z]?\)\s)/u)
    .map((unit) =>
      unit
        .replace(/^Section \d+[A-Z]* — [^(]*/u, '')
        .replace(/^\(\d{1,3}[A-Z]?\)\s*/u, '')
        .trim(),
    )
    .map((unit) => unit.replace(/[:;,—–-]+$/u, '.'));
  return (
    units.find(
      (unit) =>
        unit.length >= 60 &&
        unit.length <= 320 &&
        /\bshall\b/u.test(unit) &&
        /^[A-Z]/u.test(unit) &&
        !/\b(?:Provided|Explanation|Subs\.|Ins\.|w\.e\.f)\b/u.test(unit) &&
        !/[―‖]|̳/u.test(unit),
    ) ?? null
  );
}

function changeNumber(sentence: string): string | null {
  const swaps: Array<[RegExp, string]> = [
    [/\bthirty\b/u, 'ninety'],
    [/\bfifteen\b/u, 'twenty'],
    [/\bthree\b/u, 'five'],
    [/\btwo\b/u, 'four'],
    [/\bsix\b/u, 'nine'],
    [/\bseven\b/u, 'twelve'],
    [/\bone\b(?! person)/u, 'three'],
    [/\bten\b/u, 'twenty'],
    [/\btwenty\b/u, 'forty'],
    [/\bsixty\b/u, 'ninety'],
    [/\bone hundred\b/u, 'two hundred'],
    [/\bfirst\b/u, 'third'],
    [/\b(\d+)\b/u, 'X'],
  ];
  for (const [pattern, replacement] of swaps) {
    if (!pattern.test(sentence)) continue;
    const changed =
      replacement === 'X'
        ? sentence.replace(pattern, (digits) => String(Number(digits) + 7))
        : sentence.replace(pattern, replacement);
    if (extractNumbers(changed).join() !== extractNumbers(sentence).join()) return changed;
  }
  return null;
}

// Deterministic distractor: the next numbered section with text.
function distractorFor(section: string): LegalChunk | null {
  const index = sections.indexOf(section.toUpperCase());
  for (let offset = 1; offset < sections.length; offset += 1) {
    const candidate = graph.representative(sections[(index + offset) % sections.length]!);
    if (candidate && candidate.sectionNumber !== section) return candidate;
  }
  return null;
}

function toEvidence(chunk: LegalChunk): RagEvidence {
  return {
    chunkId: chunk.chunkId,
    documentId: chunk.documentId,
    title: chunk.actOrRegulation,
    authority: chunk.authority,
    sectionIdentifier: chunk.sectionNumber,
    sectionHeading: chunk.sectionHeading,
    pageStart: chunk.pageStart,
    pageEnd: chunk.pageEnd,
    officialSourceUrl: chunk.officialSourceUrl,
    effectiveDate: chunk.effectiveDate,
    retrievalDate: '2026-09-01T12:54:17.027Z',
    sha256: chunk.sha256,
    legalStatus: chunk.legalStatus,
    text: chunk.text,
    score: 1,
  };
}

function lowerFirst(text: string): string {
  return /^(?:A|An|The|Every|No|Where|If|Any|Each)\b/u.test(text)
    ? text[0]!.toLowerCase() + text.slice(1)
    : text;
}

function normalize(text: string): string {
  return text.normalize('NFKC').replace(/\s+/gu, ' ').toLowerCase();
}

// "7. Designated partners.— (1) Every ..." -> "Every ...": the section label
// and heading are not part of the operative sentence.
function stripSectionLabel(text: string): string {
  return text.replace(/^\d{1,3}[A-Z]{0,2}\.\s+(?:[^—\n]{2,140}?\.?\s*—\s*)?(?:\(1\)\s*)?/u, '');
}

function unseenEvidence(
  act: { act: string; documentId: string; sha256: string; officialSourceUrl: string | null },
  item: { section: string; heading: string; text: string },
): RagEvidence {
  return {
    chunkId: `${act.documentId}#${item.section}`,
    documentId: act.documentId,
    title: act.act,
    authority: 'Government of India',
    sectionIdentifier: item.section,
    sectionHeading: item.heading || null,
    pageStart: 1,
    pageEnd: 1,
    officialSourceUrl: act.officialSourceUrl,
    effectiveDate: null,
    retrievalDate: '2026-09-29T00:00:00.000Z',
    sha256: act.sha256,
    legalStatus: 'unknown',
    text: item.text,
    score: 1,
  };
}
